CREATE TABLE IF NOT EXISTS endpoint_hit (
    id          INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app         VARCHAR(100),
    uri         VARCHAR(150),
    ip          VARCHAR(30),
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT endpoint_hit_id_pk PRIMARY KEY (id)
    );